spring.application.name=gridinsight-backend

spring.datasource.url=jdbc:mysql://localhost:3306/gridinsight?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
# Base64-encoded 256-bit (32-byte) secret. Do NOT use this sample in prod.
security.jwt.secret=K8tUaSx2Pnqv4x3tG+W2zH3tqfQGx5nM2X8mZ3hQb9A=

# Access token TTL in seconds (10 minutes)
security.jwt.access-ttl-seconds=600

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration




server.port=8081

logging.level.com.gridinsight.backend=DEBUG